### ISSUE TITLE
无法运行开发服务器

### ISSUE THREAD

**Issue by KawaiiZapic** [cloudreve/frontend#85]
`yarn run start`在构建完成后一旦访问就会崩溃, 已在:5212上运行Cloudreve实例.
```
node:events:368
      throw er; // Unhandled 'error' event

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:319:11)
    at Socket.Writable.end (node:internal/streams/writable:609:17)
    at Socket.end (node:net:594:31)
    at App.welcome_screen (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/sockjs.js:54:11)
    at execute_request (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/webjs.js:22:37)
    at IncomingMessage.req.next_filter (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/webjs.js:105:18)
    at Listener.webjs_handler (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/webjs.js:107:13)
    at Listener.handler (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/sockjs.js:150:12)
    at Listener.handler (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/sockjs.js:6:59)
    at Server.<anonymous> (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/sockjs.js:157:24)
    at Server.new_handler (/home/zapic/Cloudreve/assets/node_modules/sockjs/lib/utils.js:86:19)
    at Server.emit (node:events:390:28)
    at onParserExecuteCommon (node:_http_server:727:14)
    at onParserExecute (node:_http_server:640:3)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

```
$ node -v
v16.11.1
$ yarn -v
1.22.15
```

**Comment by rhysonLin** [comment]
```bash
node -v
v16.13.1
yarn -v
1.22.17
```
出现同样问题

**Comment by monczall** [comment]
Downgrade node from v16 to v10 solved the problem, but it seems like thats not the correct way to do that.

**Comment by KawaiiZapic** [comment]
> Downgrade node from v16 to v10 solved the problem, but it seems like thats not the correct way to do that.

I solved it in a really inelegant way, modify the source code of `sockjs`, directly remove the stupid line that throwing error.
